require("samael.plugins-setup")
require("samael.core.options")
require("samael.core.keymaps")
require("samael.core.colorscheme")
require("samael.plugins.comment")
require("samael.plugins.nvim-tree")
require("samael.plugins.lualine")
require("samael.plugins.telescope")
require("samael.plugins.nvim-cmp")
require("samael.plugins.lsp.mason")
require("samael.plugins.lsp.lspsaga")
require("samael.plugins.lsp.lspconfig")
require("samael.plugins.lsp.null-ls")
require("samael.plugins.autopairs")
require("samael.plugins.treesitter")
require("samael.plugins.gitsigns")
-- require("samael.plugins.indent")
